### PR TITLE
Updated URLs to point to ECD project.

### PR DESCRIPTION
**Pull request by TylerJewell**

### CODE REVIEW

**Comment by mamacdon** [comment]
@TylerJewell can you please update the commit and add the `Signed-Off-By` footer? We need it for legal reasons.

`git commit --amend -s` should do it.

**Comment by TylerJewell** [comment]
Sorry, I don't know how to do that.

I just submitted the PR on github using their web.

Can you make the mods directyl?

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by mamacdon** [comment]
Sure -- if you don't mind me getting the author credit ;)

http://git.eclipse.org/c/orion/org.eclipse.orion.client.git/commit/?id=0fba363

**Comment by TylerJewell** [comment]
@mamacdon - lost site of this.  Circling back.  Ok with you making the mods directly.  Should you go ahead and resolve conficts and then merge?

**Comment by snorthov** [comment]
The links have been fixed for a while.

**Pull request closed without merging**
