### PR TITLE
Bug 457732 - Fix undefine in diff.js 

### PR DESCRIPTION
**Pull request by rsong6**
- Added an eslint directive to have define() as a global variable in diff.js

### CODE REVIEW

**Comment by paulweb515** [comment]
Thanks for the commit.  Could you please amend the comit to remove the 2 extra .project files and force push that commit into the branch?  Thanks

**Comment by rsong6** [comment]
Just removed the doc folder. Do you happen to know why it keeps coming up?

**Comment by paulweb515** [comment]
If you are using Eclipse+EGit the eclipse workspace will keep trying to put those .project files back until you delete them from your Eclipse workspace (the Package Explorer).  You have pushed up 2 commits.  Can you squash them and force-push up the result? Thanks.

**Comment by rsong6** [comment]
I see. Also, where can I find information on the convention for naming feature branches?

**Comment by paulweb515** [comment]
We have it on a wiki, but apparently I can't find it at the moment.  I know that we prefer branches of the type <git_id>/<meaningful branch name>.  Usually the meaningful branch name is either descriptive or bugNNNNN

**Comment by paulweb515** [comment]
Your commit seems to have the commit message repeated twice.  But I think I can just fix that with an amend before I push to the repo.

**Comment by paulweb515** [comment]
When I open the diff.js file, module still has an error.  your eslint-env has to include node as well as amd.

**Comment by paulweb515** [comment]
Closed with commit http://git.eclipse.org/c/orion/org.eclipse.orion.client.git/commit/?id=e8e535e868d2360077f809775a8e0bb4f18783ae

**Pull request closed without merging**
