### PR TITLE
Bug 457726 - Fix global undefine in gitPush.js

### PR DESCRIPTION
**Pull request by brandonadalesandro**
Bug 457726 - Fix global undefine in gitPush.js

Signed-off by: Brandon Dalesandro brandonadalesandro@gmail.com

### CODE REVIEW

**Comment by paulweb515** [comment]
Your commit message is missing the Signed-off-by.  Please amend your comment and re-add it to the pull request.

**Comment by brandonadalesandro** [comment]
Can you clarify who signed off on this, and how I should mention that in a comment?

**Comment by paulweb515** [comment]
See https://wiki.eclipse.org/Orion/Contributing_Code#Commit_your_changes for the format off the commit message.

**Comment by paulweb515** [comment]
And for the first part of your question, you are signing off on your own commit.

**Comment by paulweb515** [comment]
That looks like you've updated the PR comment.  You need to update the commit message (amend your commit) and force push it.

**Comment by brandonadalesandro** [comment]
Ok ill get that done today.

**Pull request closed without merging**
